# Generated by Django 6.1 on 2026-08-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('culto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Agenda Mensal',
                'verbose_name_plural': 'Agenda Mensal',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='AgendaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')])),
                ('horario', models.TimeField()),
                ('evento', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Agenda Semanal',
                'verbose_name_plural': 'Agenda Semanal',
                'ordering': ['dia', 'horario'],
            },
        ),
    ]
