# Generated by Django 6.1 on 2026-09-01 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=100)),
                ('introducao', models.TextField()),
                ('periodo', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('material', models.FileField(blank=True, null=True, upload_to='materiais/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
