# Generated by Django 6.1 on 2026-09-03 22:45

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='material',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/thigo/OneDrive/Desktop/Adecin/protegido')), upload_to='materiais/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
