# Generated by Django 6.1 on 2026-09-27 03:01

import comum.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebd', '0002_alter_turma_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='material',
            field=models.FileField(blank=True, null=True, storage=comum.storage.protegido, upload_to='materiais/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
