# Generated by Django 6.1 on 2026-09-01 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='gratis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='acesso',
            field=models.CharField(choices=[('publico', 'Público'), ('restrito', 'Restrito'), ('membro', 'Membro')], default='membro', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='liberados',
            field=models.ManyToManyField(blank=True, related_name='cursos_liberados', to=settings.AUTH_USER_MODEL),
        ),
    ]
