# Generated by Django 6.1 on 2026-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_aula_gratis_curso_acesso_curso_liberados'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aviso',
            field=models.CharField(blank=True, help_text='Aparece só em curso restrito. Ex.: Este curso é para o time de audiovisual.', max_length=200),
        ),
    ]
