# Generated by Django 6.1 on 2026-09-03 22:45

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_aviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/thigo/OneDrive/Desktop/Adecin/protegido')), upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
