# Generated by Django 6.1 on 2026-09-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_material_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='duracao',
        ),
    ]
