# Generated by Django 6.1 on 2026-09-27 03:01

import comum.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_aula_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='pdf',
            field=models.FileField(storage=comum.storage.protegido, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
