# Generated by Django 6.1 on 2026-09-05 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('telefone', models.CharField(help_text='número com país e DD Ex:5521987654321', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Janela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
            ],
            options={
                'ordering': ['data', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('motivo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado_pastor', 'Cancelado pelo Pastor'), ('cancelado_membro', 'Cancelado pelo Membro')], default='ativo', max_length=20)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=200)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='usuario.membro')),
            ],
            options={
                'ordering': ['data', 'horario'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ativo', 'cancelado_pastor'])), fields=('data', 'horario'), name='um_agendamento_por_horario')],
            },
        ),
    ]
