# Generated by Django 6.1 on 2026-09-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pgm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('dia', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')])),
                ('horario', models.TimeField()),
                ('lider', models.CharField(max_length=100)),
                ('contato', models.CharField(help_text='Número com país e DDD, só dígitos. Ex.: 5521987654321', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome', 'bairro'],
            },
        ),
    ]
