# Generated by Django 6.1 on 2026-09-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgm',
            name='foto',
            field=models.ImageField(default='', upload_to='pgm/'),
            preserve_default=False,
        ),
    ]
