# Generated by Django 6.1 on 2026-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgm', '0002_pgm_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgm',
            name='horario',
            field=models.TimeField(help_text='modelo (20:00)'),
        ),
    ]
