# Generated by Django 6.1 on 2026-09-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgm', '0004_pgm_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgm',
            name='categoria',
            field=models.CharField(choices=[('mulheres', 'Mulheres'), ('homens', 'Homens'), ('misto', 'Misto'), ('jovens', 'Jovens'), ('adolescentes', 'Adolescentes'), ('juniores', 'Juniores')], max_length=20),
        ),
    ]
